config/routes.rb
Rails.application.routes.draw do

  get 'user/create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  post "upvote/:comment_id", to: "votes#trigger"

  post "agree_vote/:topic_id/:is_agree", to: "agree_votes#trigger"

  get 'category/:category_name', to: "topics#index"

  resources :categories

  resources :comments

  resources :topics

  resources :users

  root "topics#daily"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :user

	has_many :comments

	has_many :topic_categories
	has_many :categories, through: :topic_categories

	has_many :agree_votes

	validates_length_of :title, :minimum => 3, :minimum => 10

	def render_description
		renderer = WikiRender.new(filter_html: true, hard_wrap: true)
		markdown = Redcarpet::Markdown.new(renderer, autolink: true, no_intra_emphasis: true)
		markdown.render(self.description)
	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    if params[:category_name]
      @category = Category.find_by_name(params[:category_name])
      @topics = @category.topics.all.order("CREATED_AT DESC")
    else
      @topics = Topic.all.order("CREATED_AT DESC")
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    # If daily topic, redirect
    if @topic == Topic.where(is_daily_topic: true).first
      redirect_to root_path
    end

    @agree_comments = @topic.comments.where(is_agree: true)
    @disagree_comments = @topic.comments.where(is_agree: false)
  end

  def daily
    @topic = Topic.where(is_daily_topic: true).first
    gon.topic = @topic

    @total_votes = @topic.agree_votes_override.to_i + @topic.disagree_votes_override.to_i + @topic.agree_votes.count
    @agree_count = @topic.agree_votes_override.to_i + @topic.agree_votes.where(is_agree: true).count
    @disagree_count = @topic.disagree_votes_override.to_i + @topic.agree_votes.where(is_agree: false).count

    @agree_comments = @topic.comments.where(is_agree: true).sort_by { |comment| -1 * comment.score }

    @disagree_comments = @topic.comments.where(is_agree: false).sort_by { |comment| -1 * comment.score }

    if Time.now.hour >= 10
      end_time = Time.new(Time.now.year, Time.now.month, Time.now.day + 1, 10)
    else
      end_time = Time.new(Time.now.year, Time.now.month, Time.now.day, 10)
    end

    @time_left = TimeDifference.between(Time.now, end_time).in_general

    render :show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
    gon.categories = Category.all
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @category_names = JSON.parse(params[:topic][:categories])

    @topic = Topic.new(title: topic_params[:title])

    @topic.user = current_user

    if @topic.save
      @category_names.each do |name|
        # Check if it exists
        if !Category.find_by_name(name).blank?
          @topic.topic_categories.create(category_id: Category.find_by_name(name).id)
        else
          category = Category.create(name: name)
          @topic.topic_categories.create(category_id: category.id)
        end
      end

      if current_user
        redirect_to @topic, notice: "topic published."
      else
        session[:unsaved_topic] = @topic.id
        redirect_to "/auth/facebook"
      end
    else
      gon.categories = Category.all
      render :new
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :categories)
    end

    def correct_user
      if @topic.user != current_user
        redirect_to topics_path, notice: "You may only edit topics you own."
      end
    end
end

app/views/topics/_comment.html.erb
<article class="comment <%= c.is_agree ? 'agreeComment' : 'disagreeComment'%>" data-comment-id="<%= c.id %>">
  <p class="commentInfo">
    <% active_class = Vote.where(user: current_user, comment_id: c.id).exists? ? 'active' : '' %>
    <i class="upvote glyphicon glyphicon-chevron-up <%= active_class %>"></i>
    <%= c.score %>
    &nbsp;
    <%= link_to c.user.name, c.user %>
  </p>
  <%= raw(c.render_content) %>
</article>

app/views/topics/_comment_form.html.erb
<%= form_for Comment.new, class: "commentForm" do |f| %>
  <%= f.hidden_field :topic_id, value: @topic.id %>
  <%= f.hidden_field :is_agree, value: is_agree %>
  <div class="form-group">
    <% placeholder_text = is_agree ? "Why do you agree?" : "Why do you disagree?" %>
    <%= f.text_area :content, rows: 2, class: "form-control", placeholder: placeholder_text %>
  </div>
  <%= f.submit class: "submitCommentBtn btn btn-small btn-primary hidden", value: "Post" %>
<% end %>

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <p>
        Ruh-roh! We need you to change something with your opinion:
      </p>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><strong><%= message %></strong></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Opinion</label>
    <%= f.text_field :title, placeholder: "Religion causes wars.", class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Categories</label> <small class="text-muted">Helps relevant people discover your opinion.</small>
    <select
      id="categories"
      multiple
      placeholder="Choose from existing categories, or add your own.">
    </select>
    <%= f.hidden_field :categories, id: "topic_categories" %>
  </div>
  <div class="actions">
    <%= f.submit "Post Opinion", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/topics/_vote_buttons_and_form.html.erb
<div class="voteActionsContainer <%= params["action"] == "show" ? "showPage" : "" %>" data-topic-id="<%= topic.id %>">
  <div class="topicFooter">
    <div class="btn-group topicActions">
      <% agree_active_class = current_user && topic.agree_votes.where(is_agree: true, user_id: current_user.id).count > 0 ? 'active' : '' %>
      <% disagree_active_class = current_user && topic.agree_votes.where(is_agree: false, user_id: current_user.id).count > 0 ? 'active' : '' %>
      <% button_size_class = params["action"] == "index" ? "btn-xs" : "" %>
      <button class="btn btn-default <%= button_size_class %> voteBtn agree smallCaps <%= agree_active_class %>" data-is-agree="1">
        agree
        <small class="agreeVoteCount"><%= topic.agree_votes.where(is_agree: true).count %></small>
      </button>
      <button class="btn btn-default <%= button_size_class %> voteBtn disagree smallCaps <%= disagree_active_class %>" data-is-agree="0">
        disagree
        <small class="disagreeVoteCount"><%= topic.agree_votes.where(is_agree: false).count %></small>
      </button>
    </div>
    &nbsp;
    <% if topic.comments.count > 0 %>
      <span class="text-muted answerCount"><%= pluralize(topic.comments.count, "comment") %></span>
    <% end %>
  </div>

  <div class="agreeCommentForm hidden">
    <br/>
    <%= form_for Comment.new do |f| %>
      <%= f.hidden_field :topic_id, value: topic.id %>
      <%= f.hidden_field :is_agree, value: 1 %>
      <div class="form-group">
        <label>Why do you agree? <small class="text-muted">Optional</small></label>
        <% placeholder_text = 1 ? "Why do you agree?" : "Why do you disagree?" %>
        <%= f.text_area :content, rows: 10, class: "form-control", placeholder: "Enter explanation..." %>
      </div>
      <%= f.submit class: "submitCommentBtn btn btn-small btn-primary", value: "Post" %>
    <% end %>
  </div>
  <div class="disagreeCommentForm hidden">
    <br/>
    <%= form_for Comment.new do |f| %>
      <%= f.hidden_field :topic_id, value: topic.id %>
      <%= f.hidden_field :is_agree, value: 0 %>
      <div class="form-group">
        <label>Why do you disagree? <small class="text-muted">Optional</small></label>
        <% placeholder_text = 0 ? "Why do you agree?" : "Why do you disagree?" %>
        <%= f.text_area :content, rows: 10, class: "form-control", placeholder: "Enter explanation..." %>
      </div>
      <%= f.submit class: "submitCommentBtn btn btn-small btn-primary", value: "Post" %>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<div class="container">
	<h1>Editing topic</h1>

	<%= render 'form' %>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="alert alert-info indexHeader">
        <div class="lead">
          <p>
            2Sided is a place where opinions are respectfully debated.
          </p>
          <p class="antiTroll">
            To maintain healthy debate, only post serious comments.  We're here to educate each other and learn from different perspectives.
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="topicsFeed col-sm-9">
      <% if params[:category_name] %>
        <div class="alert alert-warning categoryFilterAlert">
          Opinions on <strong><%= @category.name.gsub(/-/, " ").titlecase %></strong>
          <a href="/" class="pull-right removeFilters">
            <small>Remove Filter</small> <i class="glyphicon glyphicon-remove"></i>
          </a>
        </div>
      <% end %>

      <% @topics.each do |topic| %>
        <div class="topicContainer">
          <div class="topic">
            <p class="smallCaps topicMetaInfo">
              <img class="squareAvatar"
              src="https://graph.facebook.com/<%= topic.user.uid %>/picture?width=32&height=32"
              height="14px">
              opinion on

              <%= topic.categories.map { |cat| link_to(cat.name.downcase, "/category/#{cat.name.parameterize}") }.join(', ').html_safe %>
            </p>

            <h4 class="title">
              <%= link_to topic.title, topic, class: "topicLink" %>
            </h4>

            <%= render partial: "vote_buttons_and_form", locals: {topic: topic} %>

          </div>
        </div>
      <% end %>
    </div>
    <div class="categoryContainer col-sm-3">
      <h3 class="contentHeader">filter</h3>
      <ul class="filters">
        <% Category.all.each do |category| %>
          <%
            if category.topics.count == 0
              next
            end
          %>
          <% active_class = category == @category ? 'active' : '' %>
          <% link = category == @category ? '/' : '/category/' + category.name.parameterize %>
          <li class="<%= active_class %>">
            <a href="<%= link %>"
              data-toggle="tooltip"
              data-placement="top"
              title="<%= category.description %>">
              <%= category.name.gsub( /-/, ' ' ).downcase %>
              <span class="count">
                <%= category.topics.count %>
              </span>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container">
	<h1>New Opinion</h1>

	<%= render 'form' %>
</div>

app/views/topics/show.html.erb
<header>
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<%= notice %>

				<% if false %>
					<div class="btn-group pull-right">
						<% if @topic.user == current_user %>
							<%= link_to topic_path(@topic), method: "delete", class: "btn btn-danger btn-sm" do %>
								<i class="glyphicon glyphicon-remove"></i>
								Delete Topic
							<% end %>
						<% end %>
					</div>
				<% end %>

				<h1><%= @topic.title %></h1>
				<p class="countDown">
					<span>Ends in </span><span class="time">
					<%= pluralize(@time_left[:hours], "hours") %> <%= pluralize(@time_left[:minutes], "minutes") %></span>
				</p>

				<% if false %>
					<p class="topicMetaInfo">
						<span class="text-muted">submitted <%= time_ago_in_words(@topic.created_at) %> ago by</span>
						<%= link_to @topic.user.name, @topic.user %>
					</p>
				<% end %>
			</div>
		</div>
	</div>
</header>

<% agree_active_class = current_user && @topic.agree_votes.where(is_agree: true, user_id: current_user.id).count > 0 ? 'active' : '' %>
<% disagree_active_class = current_user && @topic.agree_votes.where(is_agree: false, user_id: current_user.id).count > 0 ? 'active' : '' %>

<section class="voteButtonsContainer">
	<div class="clearfix">
		<div class="agreeVoteContainer">
			<button class="topicAgreeBtn btn btn-default smallCaps <%= agree_active_class %>" data-is-agree="1">
				agree
				<small class="badge agreeVoteCount">
					<%= @agree_count %>
				</small>
			</button>
		</div>
		<div class="disagreeVoteContainer">
			<button class="topicDisagreeBtn btn btn-default smallCaps <%= disagree_active_class %>" data-is-agree="0">
				disagree
				<small class="badge disagreeVoteCount">
					<%= @disagree_count %>
				</small>
			</button>
		</div>
	</div>
	<div class="agreeBorder"></div>
	<div class="disagreeBorder"></div>
</section>

<main>
	<div class="container">
		<div class="row">
			<div class="col-sm-6">

				<div class="agreeCommentForm hidden">
			    <br/>
			    <%= form_for Comment.new do |f| %>
			      <%= f.hidden_field :topic_id, value: @topic.id %>
			      <%= f.hidden_field :is_agree, value: 1 %>
			      <div class="form-group">
			        <label>Why do you agree? <small class="text-muted">Optional</small></label>
			        <% placeholder_text = 1 ? "Why do you agree?" : "Why do you disagree?" %>
			        <%= f.text_area :content, rows: 10, class: "form-control", placeholder: "Enter explanation..." %>
			      </div>
			      <%= f.submit class: "submitCommentBtn btn btn-small btn-primary", value: "Post" %>
			    <% end %>
			  </div>

				<section class="comments">
					<% if @agree_comments.count > 0 %>
						<% @agree_comments.each do |c| %>
							<%= render partial: "comment", locals: {c: c} %>
						<% end %>
					<% else %>
						<br/>
						<h5 class="text-muted">No comments for "agree".</h5>
					<% end %>
				</section>
			</div>

			<div class="col-sm-6">
				<div class="disagreeCommentForm hidden">
			    <br/>
			    <%= form_for Comment.new do |f| %>
			      <%= f.hidden_field :topic_id, value: @topic.id %>
			      <%= f.hidden_field :is_agree, value: 0 %>
			      <div class="form-group">
			        <label>Why do you disagree? <small class="text-muted">Optional</small></label>
			        <% placeholder_text = 0 ? "Why do you agree?" : "Why do you disagree?" %>
			        <%= f.text_area :content, rows: 10, class: "form-control", placeholder: "Enter explanation..." %>
			      </div>
			      <%= f.submit class: "submitCommentBtn btn btn-small btn-primary", value: "Post" %>
			    <% end %>
			  </div>

				<section class="comments">
					<% if @disagree_comments.count > 0 %>
						<% @disagree_comments.each do |c| %>
							<%= render partial: "comment", locals: {is_agree: false, c: c} %>
						<% end %>
					<% else %>
						<br/>
						<h5 class="text-muted">No comments for "disagree".</h5>
					<% end %>
				</section>
			</div>
		</div>
	</div>
</main>