config/routes.rb
Rails.application.routes.draw do

  get 'user/create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  post "upvote/:comment_id", to: "votes#trigger"

  post "agree_vote/:topic_id/:is_agree", to: "agree_votes#trigger"

  get 'category/:category_name', to: "topics#index"

  resources :categories

  resources :comments

  resources :topics

  resources :users

  root "topics#daily"

end

app/views/layouts/_daily_top_nav.html.erb
<nav class="navbar navbar-default" id="dailyTopNav" role="navigation">
  <div class="container-fluid container">
    <div class="row">
      <div class="col-xs-12">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "The Daily Debate", root_path, :class => "navbar-brand"  %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if current_user %>
              <a href="#">
                <img class="avatar profileAvatar" src="https://graph.facebook.com/<%= current_user.uid %>/picture?width=64&height=64" height="22px">
                &nbsp;
                <%= current_user.name %>
              </a>
            <% else %>
              <div class="nav navbar-nav navbar-right">
                <%= link_to 'Subscribe', "#", class: "btn btn-primary navbar-btn subscribeBtn" %>
              </div>
              <%= form_for User.new, remote: true, html: {class: "navbar-form navbar-right hidden subscribeForm"} do |f| %>
                <div class="form-group">
                  <%= f.text_field :email, class: "form-control", placeholder: "me@gmail.com" %>
                  <%= f.hidden_field :is_subscribed, value: "true" %>
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
              <% end %>
              <p class="subscribeSuccessMsg hidden">You're subscribed!</p>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_footer.html.erb
<footer class="siteFooter">
  <div class="container">
    <a href="/about">About</a>
    <a href="/topics">Archive</a>
    <% if current_user %>
      <a href="/signout">Sign Out</a>
    <% else %>
      <a href="/auth/facebook">Sign In</a>
    <% end %>
  </div>
</footer>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56786925-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_mixpanel.html.erb
<!-- start Mixpanel --><script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("1fde97671a5d66a3d6801bfc0c93e2d4");</script><!-- end Mixpanel -->

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="topNav" role="navigation">
  <div class="container-fluid container">
    <div class="row">
      <div class="col-xs-12">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "2Sided", root_path, :class => "navbar-brand"  %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="nav navbar-nav navbar-right">
          <%= link_to raw('<small><i class="glyphicon glyphicon-comment"></i></small> Post Opinion'), new_topic_path, class: "btn btn-primary navbar-btn postOpinionBtn" %>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if current_user %>
              <a href="#"
                class="dropdown-toggle"
                data-toggle="dropdown">
                <img class="avatar profileAvatar" src="https://graph.facebook.com/<%= current_user.uid %>/picture?width=64&height=64" height="22px">
                &nbsp; <%= current_user.name %>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">My Statements</a></li>
                <li class="divider"></li>
                <li><a href="/signout">Log Out</a></li>
              </ul>
            <% else %>
              <form class="navbar-form">
                <%= link_to "Sign in with Facebook", "/auth/facebook", class: "btn btn-primary", id: "sign_in" %>
              </form>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</nav>

<div class="topNavSpacer">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Daily Debate</title>
  <%= include_gon %>
  <%= favicon_link_tag 'favicon.ico' %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag    params[:controller] + "_" + params[:action] %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag params[:controller] %>
  <%= javascript_include_tag params[:controller] + "_" + params[:action] %>
  <%= csrf_meta_tags %>

</head>
<body>
	<%= render "layouts/daily_top_nav" %>

	<%= yield %>

  <%= render "layouts/footer" %>

  <%= render "layouts/google_analytics" %>
  <%= render "layouts/mixpanel" %>
  <script>
    if (gon && gon.user) {
      mixpanel.identify(gon.user.id);
    }
  </script>
</body>
</html>